### ISSUE TITLE
Anaconda Compatibility

### ISSUE THREAD

**Issue by BGriffy78** [KeyWeeUsr/KivyInstaller#11]
** Not an issue! **

This installer is f#*@ing awesome!  Fantastic work!!

I have a question, sorry to throw it in with the issues, but I had to ask...

Is it possible to use this KivyInstaller to setup an Anaconda virtual environment?  I've been messing around trying to get it working all day and am not really getting anywhere.  This installer worked first time but its for a standalone python install.

Do you know of any way I can use this installer within an Anaconda environment?

Thanks!!!

**Comment by KeyWeeUsr** [comment]
I have no knowledge about how anaconda installs or what anaconda virtual environment is, however, I don't intend to add any `venv` functionality into this installer as its a matter of personal opinion (not) to use venv of users. Anyway, I doubt you can install anaconda *directly* with this installer. You'd need to find out what anaconda uses for its installer and then hope that the installer provides some console access. If it does, then you can create a similar wrapper for the installation as I did in `kivy.bat`.

If this isn't about installing the whole anaconda from scratch, but just about installing Kivy to anaconda, just placing `kivy.bat` into the python folder should be enough for it to detect that python is already installed and it should proceed with the rest of the installing process like with a casual python.

Just a note, do that in some separate anaconda installation as it might cripple it in the process e.g. if some file isn't in place.
