### ISSUE TITLE
bitsadmin fails

### ISSUE THREAD

**Issue by miikeat** [KeyWeeUsr/KivyInstaller#5]
When i try to execute this line from readme.md

    bitsadmin /transfer "GetBatch" "https://git.io/vDDjn" "%cd%\kivy.bat"

It fails with "invalid command" and prints the usage screen.

System: Windows 10 Build 14393.693

**Comment by KeyWeeUsr** [comment]
Ah, so apparently it's happening. I hoped they'd just forget about its deprecation. Anyway, it's mentioned [in the file directly](https://github.com/KeyWeeUsr/KivyInstaller/blob/master/kivy.bat#L6) where it's available, so try to download it back if possible for Win10 and then it should work fine.

I was considering writing it in Powershell, but the versions of it seems to vary, yet Batch JustWorks(tm). Well, not in this case I presume.

I'll write some check for `bitsadmin.exe` as I should have already done before and just use Powershell for downloading like in [AppVeyor](https://github.com/KeyWeeUsr/KivyInstaller/blob/master/appveyor.yml#L117).

**Comment by miikeat** [comment]
No, bitsadmin is still there, it also says it's depricated, but then it says invalid command and prints the usage screen...
I think there is some problem with the /transfer command of bitsadmin.

**Comment by KeyWeeUsr** [comment]
Well, I'm confused... Please paste the whole log after the instructions, because the `bitsadmin.exe` works correctly for me.

**Comment by miikeat** [comment]
I'm currently only on my phone but i will do it tomorrow!

**Comment by miikeat** [comment]
Sorry, my fault!
I was running the command from git bash and didn't think yesterday much about it, but some commands just don't work there, maybe the %cd% messes up the command.
in cmd and powershell everything works fine!
