### ISSUE TITLE
Explanation to launch your app

### ISSUE THREAD

**Issue by Zen-CODE** [KeyWeeUsr/KivyInstaller#8]
Having built the new python environment, it's not at all clear how to use it to launch your app. An explanation of how to do this would go a long way.

**Comment by KeyWeeUsr** [comment]
I'm not quite sure if I understand right. What's not clear? To run the installer there are instructions in the Readme.md. After python + kivy are installed there are two ways how to proceed (that part isn't clear?):

* run `kivy.bat`
* run simple `cmd.exe`

If the kivy.bat is run, then it brings all the console options mentioned in the docs. If not, then it's just running python from a clean console.

If the console options are available, then such things like quick packaging of simple scripts that don't require 3rd party packages are easy to use (`kivy pack file.py`).

**Comment by Zen-CODE** [comment]
Running kivy.bat just puts you into the environment. You can install, but there is no explanation of how to run your app. e.g. kivy.bat C:\MyApp\main.py Seems obvious, but it's not to everyone.

**Comment by Zen-CODE** [comment]
Okay, I see now there is an explanation for launching when running kivy.bat after installation,.
